### ISSUE TITLE
Issue in running the train_DESI.py script

### ISSUE THREAD

**Issue by eduardo-hartmann** [pmelchior/spender#55]
I'm attempting to run the train_DESI.py script in the following way

$ python train_DESI.py <data> <output> -b 256 -l 10 -zmax 0.45 -v

And the following error is raised:

File "/opt/SIE/ML/miniconda3/envs/ml_py310_cuda_12.3/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in applyreturn user_fn(self, *args)
File “/home/hartmann/.local/ml_py310_cuda_12.3/lib/python3.10/site-packages/torchinterp1d/interp1d.py",  line 155, in backwardgradients = torch.autograd.grad(
File "/opt/SIE/ML/miniconda3/envs/ml_py310_cuda_12.3/lib/python3.10/site-packages/torch/autograd/__init__.py",
line 394, in gradresult = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass   
RuntimeError: Resource temporarily unavailable

This seems to be an issue in the backwards pass. I've tried downgrading and upgrading the related modules (PyTorch, Accelerate). The data was downloaded using the save_in_batches function from the desi.py script. Any ideas on what's causing this?

**Comment by eduardo-hartmann** [comment]
Hello, I've tried turning on all the options presented like this:

$ python3 train_DESI.py <data_dir> <output.file>  -b 256 -l 10 -r 1e-5 -a -s -c -zmax 0.45 -v

And I get a different error:

Traceback (most recent call last):
  File "/home/hartmann/Research/DESI/train_DESI_mod.py", line 476, in <module>
    train(models, instruments, trainloaders, validloaders, n_epoch=n_epoch,
  File "/home/hartmann/Research/DESI/train_DESI_mod.py", line 304, in train
    losses = get_losses(
  File "/home/hartmann/Research/DESI/train_DESI_mod.py", line 174, in get_losses
    batch_copy = aug_fct(batch,z_max=args.z_max)
  File "/home/hartmann/Research/DESI/spender/spender/data/desi.py", line 554, in augment_spectra
    spec_new = Interp1d()(wave_obs.repeat(batch_size,1), spec, wave_redshifted).float()
  File "/home/hartmann/.virtualenvs/SBI/lib/python3.10/site-packages/torch/autograd/function.py", line 451, in __call__
    raise RuntimeError(
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

Is there a specific version of torch I should be using? This non-static forward method seems to have changed some time ago. Thanks in advance for any tips :)

**Comment by pmelchior** [comment]
This last error was caused by an outdated call. Should be fixed now in master and in spender 0.2.7
